- name: "BECFG100.01 update"
  become: true
  shell: |
    apt-get -y update

- name: "BECFG100.02 install python3.6"
  become: true
  shell: |
    apt-get -y install python3.6

- name: "BECFG100.03 install nodejs"
  become: true
  shell: |
    apt-get -y install build-essential
    apt-get -y install curl openssl libssl-dev
    curl -sL https://deb.nodesource.com/setup_14.x | bash -
    apt -y install nodejs

- name: "BECFG100.04 install pm2"
  become: true
  shell: |
    npm install pm2 -g