- name: BEUP100 udapeople prerequisites
  include_tasks: BEUP100_prerequsites.yml

#- name: BEUP300 setup pm2
  #include_tasks: BEUP300_setup_PM2.yml

- name: BEUP400 run application
  include_tasks: BEUP400_run_app.yml