version: 2.1

orbs:
  slack: circleci/slack@4.1.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          key: v1-frontend-build
          paths:
            - ~/project/frontend/node_modules

  build-backend:
    docker:
      - image: circleci/node:13.8.0

    #environment:
      #GIT_COMMIT_DESC: git log --format=%B -n 1 $CIRCLE_SHA1

    steps:
      - checkout
      - run:
          name: Backend build
          command: |
            cd backend
            npm i
            npm run build
            echo "export COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
            source $BASH_ENV

      - slack/notify:
          channel: C01FC0ZPENR
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *faild* :octagonal_sign: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME\n\ncommit message: $COMMIT_MESSAGE"
                  }
                }
              ]
            }

      - slack/notify:
          channel: C01FC0ZPENR
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *built* :white_check_mark: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME\n\ncommit message: $COMMIT_MESSAGE"
                  }
                }
              ]
            }

      - save_cache:
          key: v1-backend-build
          paths:
            - ~/project/backend/node_modules

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: v1-frontend-build

      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm i
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: v1-backend-build

      - run:
          name: Run backend tests
          command: |
            cd backend
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: frontend-build

      - run:
          name: Scan frontend depedencies
          command: |
            cd frontend
            npm audit --audit-level=critical


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: backend-build

      - run:
          name: Scan backend depedencies
          command: |
            cd backend
            npm audit --audit-level=critical

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout

      - run:
          name: install prerequsites
          command: |
            yum -y install tar gzip

      - run:
          name: Ensure back-end infrastructure exists
          command: |
            # build-backend:
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
#      - run:
#          name: Ensure front-end infrastructure exist
#          command: |
#            # build-frontend:
#            aws cloudformation deploy \
#            --template-file .circleci/files/frontend.yml \
#            --tags project=udapeople \
#            --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
#            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"

      - run:
          name: Add back-end ip to ansible inventory
          command: |
            backendDns=`aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --query "Reservations[*].Instances[*].[PublicDnsName]" \
              --output text`

            echo $backendDns >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt

            # put it in the shared memory
            curl -H "Content-Type: text/plain" \
              -H "token: e38aee29-a976-4696-843d-2d115c52219a" \
              --request PUT \
              --data "$backendDns" https://api.memstash.io/values/backendDns

      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      # Here's where you will add some code to rollback on failure

workflows:
  default:
    jobs:
      #- build-frontend
      #- build-backend:
          #context: basic
      - deploy-infrastructure
          #- test-frontend:
          # requires: [build-frontend]
          # - test-backend:
          #   requires: [build-backend]
          # - scan-backend:
          #     requires: [build-backend]
          # - scan-frontend:
          #requires: [build-frontend]