version: 2.1
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Frontend Build
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          key: v1-frontend-build
          paths:
            - ~/project/frontend/node_modules

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Backend build
          command: |
            cd backend
            npm i
            npm run build

      - save_cache:
          key: v1-backend-build
          paths:
            - ~/project/backend/node_modules

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: v1-frontend-build

      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm i
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: v1-backend-build

      - run:
          name: Run backend tests
          command: |
            cd backend
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: frontend-build

      - run:
          name: Scan frontend depedencies
          command: |
            cd frontend
            npm audit --audit-level=critical


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - restore_cache:
          key: backend-build

      - run:
          name: Scan backend depedencies
          command: |
            cd backend
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - build-frontend
      #- build-backend
      - test-frontend:
          requires: [build-frontend]
      #- test-backend:
       #   requires: [build-backend]
      #- scan-backend:
       #   requires: [build-backend]
      #- scan-frontend:
          #requires: [build-frontend]